/// <reference types="node" />
import { PrismaClient } from '../generated/prisma';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seeding...');

  // Create sample users/executives
  const users = await Promise.all([
    prisma.user.upsert({
      where: { exeId: 'EXE001' },
      update: {},
      create: {
        exeId: 'EXE001',
        companyId: 'LGLMKT',
        password: 'LGLMKT', // In production, this should be hashed
        leader: 'LEADER001',
        areaCode: 'CMB',
        exeName: 'John Doe',
        exeNameOrig: 'CMB:John Doe-001',
        role: 'Sales Executive',
        areaName: 'COLOMBO',
        region: 'Western',
        subdivisionCode: 'SUB001',
        imageLocation: '/images/executives/exe001.jpg',
        isActive: true,
      },
    }),
    prisma.user.upsert({
      where: { exeId: 'EXE002' },
      update: {},
      create: {
        exeId: 'EXE002',
        companyId: 'LGLMKT',
        password: 'LGLMKT',
        leader: 'LEADER001',
        areaCode: 'KAL',
        exeName: 'Jane Smith',
        exeNameOrig: 'KAL:Jane Smith-002',
        role: 'Area Sales Manager',
        areaName: 'KALUTARA',
        region: 'Western',
        subdivisionCode: 'SUB002',
        imageLocation: '/images/executives/exe002.jpg',
        isActive: true,
      },
    }),
  ]);

  console.log('✅ Users created:', users.length);

  // Create sample customers
  const customers = await Promise.all([
    prisma.customer.upsert({
      where: { customerId: 'CUST001' },
      update: {},
      create: {
        customerId: 'CUST001',
        exeId: 'EXE001',
        customerName: 'Colombo Hardware Store',
        addr1: '123 Main Street',
        addr2: 'Colombo 01',
        addr3: '',
        city: 'Colombo',
        route: 'Route A',
        phone1: '+94112345678',
        phone2: '+94112345679',
        phone3: '',
        additional: 'Additional info',
        isActive: true,
        grade: 'A',
        contactName: 'Mr. Hardware Owner',
        contactPhone: '+94112345680',
        startDate: new Date('2020-01-01'),
        creditLimit: 1000000.00,
        creditPeriod: 30,
        comments: 'Reliable customer',
        lastInvoiceDate: new Date('2024-01-15'),
        lastInvoiceAmt: 50000.00,
        lastPaymentDate: new Date('2024-01-10'),
        lastPaymentAmt: 45000.00,
        isInactive: false,
        isHold: false,
        followupStatus: 'Active',
        location: '6.9271,79.8612',
      },
    }),
    prisma.customer.upsert({
      where: { customerId: 'CUST002' },
      update: {},
      create: {
        customerId: 'CUST002',
        exeId: 'EXE001',
        customerName: 'Kalutara Construction Co',
        addr1: '456 Industrial Road',
        addr2: 'Kalutara',
        addr3: '',
        city: 'Kalutara',
        route: 'Route B',
        phone1: '+94112345681',
        phone2: '+94112345682',
        phone3: '',
        additional: 'Construction company',
        isActive: true,
        grade: 'B',
        contactName: 'Mr. Construction Manager',
        contactPhone: '+94112345683',
        startDate: new Date('2021-03-15'),
        creditLimit: 2000000.00,
        creditPeriod: 45,
        comments: 'Large construction projects',
        lastInvoiceDate: new Date('2024-01-20'),
        lastInvoiceAmt: 150000.00,
        lastPaymentDate: new Date('2024-01-18'),
        lastPaymentAmt: 120000.00,
        isInactive: false,
        isHold: false,
        followupStatus: 'Active',
        location: '6.5833,79.9593',
      },
    }),
  ]);

  console.log('✅ Customers created:', customers.length);

  // Create sample products
  const productUpserts = [
    prisma.product.upsert({
      where: { itemCode: 'HW001' },
      update: {},
      create: {
        itemCode: 'HW001',
        description: 'Steel Nails 3 inch (DIS 10%)',
        category: 'Hardware',
        subCategory: 'Nails',
        categoryCode: 'HW',
        uom: 'KG',
        price: 500.00,
        qty: 100,
        imageUrl: 'https://example.com/images/hw001.jpg',
        discountAmount: 50.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW002' },
      update: {},
      create: {
        itemCode: 'HW002',
        description: 'Cement Portland 50kg',
        category: 'Building Materials',
        subCategory: 'Cement',
        categoryCode: 'BM',
        uom: 'BAG',
        price: 1200.00,
        qty: 50,
        imageUrl: 'https://example.com/images/hw002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'LT001' },
      update: {},
      create: {
        itemCode: 'LT001',
        description: 'LED Bulb 9W Warm White',
        category: 'Lighting',
        subCategory: 'LED Bulbs',
        categoryCode: 'LT',
        uom: 'PCS',
        price: 250.00,
        qty: 200,
        imageUrl: 'https://example.com/images/lt001.jpg',
        discountAmount: 25.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL001' },
      update: {},
      create: {
        itemCode: 'EL001',
        description: 'Electrical Wire 2.5mm',
        category: 'Electrical',
        subCategory: 'Wires',
        categoryCode: 'EL',
        uom: 'MTR',
        price: 150.00,
        qty: 500,
        imageUrl: 'https://example.com/images/el001.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    // Additional products for more variety
    prisma.product.upsert({
      where: { itemCode: 'HW003' },
      update: {},
      create: {
        itemCode: 'HW003',
        description: 'Screw Driver Set (6 pcs)',
        category: 'Hardware',
        subCategory: 'Tools',
        categoryCode: 'HW',
        uom: 'SET',
        price: 850.00,
        qty: 75,
        imageUrl: 'https://example.com/images/hw003.jpg',
        discountAmount: 85.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW004' },
      update: {},
      create: {
        itemCode: 'HW004',
        description: 'Hammer 1kg Steel Handle',
        category: 'Hardware',
        subCategory: 'Tools',
        categoryCode: 'HW',
        uom: 'PCS',
        price: 450.00,
        qty: 120,
        imageUrl: 'https://example.com/images/hw004.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'BM001' },
      update: {},
      create: {
        itemCode: 'BM001',
        description: 'Sand Fine (River)',
        category: 'Building Materials',
        subCategory: 'Sand',
        categoryCode: 'BM',
        uom: 'M3',
        price: 3500.00,
        qty: 25,
        imageUrl: 'https://example.com/images/bm001.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'BM002' },
      update: {},
      create: {
        itemCode: 'BM002',
        description: 'Bricks Red (Standard)',
        category: 'Building Materials',
        subCategory: 'Bricks',
        categoryCode: 'BM',
        uom: 'PCS',
        price: 25.00,
        qty: 5000,
        imageUrl: 'https://example.com/images/bm002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'LT002' },
      update: {},
      create: {
        itemCode: 'LT002',
        description: 'Tube Light 4ft 36W',
        category: 'Lighting',
        subCategory: 'Tube Lights',
        categoryCode: 'LT',
        uom: 'PCS',
        price: 180.00,
        qty: 150,
        imageUrl: 'https://example.com/images/lt002.jpg',
        discountAmount: 18.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'LT003' },
      update: {},
      create: {
        itemCode: 'LT003',
        description: 'Ceiling Fan 48 inch',
        category: 'Lighting',
        subCategory: 'Fans',
        categoryCode: 'LT',
        uom: 'PCS',
        price: 3500.00,
        qty: 30,
        imageUrl: 'https://example.com/images/lt003.jpg',
        discountAmount: 350.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL002' },
      update: {},
      create: {
        itemCode: 'EL002',
        description: 'MCB 32A Single Pole',
        category: 'Electrical',
        subCategory: 'Circuit Breakers',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 450.00,
        qty: 80,
        imageUrl: 'https://example.com/images/el002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL003' },
      update: {},
      create: {
        itemCode: 'EL003',
        description: 'Socket 13A Double',
        category: 'Electrical',
        subCategory: 'Sockets',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 280.00,
        qty: 200,
        imageUrl: 'https://example.com/images/el003.jpg',
        discountAmount: 28.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL001' },
      update: {},
      create: {
        itemCode: 'PL001',
        description: 'PVC Pipe 4 inch',
        category: 'Plumbing',
        subCategory: 'Pipes',
        categoryCode: 'PL',
        uom: 'MTR',
        price: 1200.00,
        qty: 100,
        imageUrl: 'https://example.com/images/pl001.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL002' },
      update: {},
      create: {
        itemCode: 'PL002',
        description: 'Tap Mixer Chrome',
        category: 'Plumbing',
        subCategory: 'Taps',
        categoryCode: 'PL',
        uom: 'PCS',
        price: 850.00,
        qty: 60,
        imageUrl: 'https://example.com/images/pl002.jpg',
        discountAmount: 85.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA001' },
      update: {},
      create: {
        itemCode: 'PA001',
        description: 'Paint White 20L',
        category: 'Paint',
        subCategory: 'Interior',
        categoryCode: 'PA',
        uom: 'CAN',
        price: 4500.00,
        qty: 40,
        imageUrl: 'https://example.com/images/pa001.jpg',
        discountAmount: 450.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA002' },
      update: {},
      create: {
        itemCode: 'PA002',
        description: 'Paint Brush 2 inch',
        category: 'Paint',
        subCategory: 'Brushes',
        categoryCode: 'PA',
        uom: 'PCS',
        price: 120.00,
        qty: 300,
        imageUrl: 'https://example.com/images/pa002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG001' },
      update: {},
      create: {
        itemCode: 'SG001',
        description: 'Safety Helmet Yellow',
        category: 'Safety Gear',
        subCategory: 'Helmets',
        categoryCode: 'SG',
        uom: 'PCS',
        price: 350.00,
        qty: 150,
        imageUrl: 'https://example.com/images/sg001.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG002' },
      update: {},
      create: {
        itemCode: 'SG002',
        description: 'Safety Gloves Leather',
        category: 'Safety Gear',
        subCategory: 'Gloves',
        categoryCode: 'SG',
        uom: 'PAIR',
        price: 280.00,
        qty: 200,
        imageUrl: 'https://example.com/images/sg002.jpg',
        discountAmount: 28.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL001' },
      update: {},
      create: {
        itemCode: 'TL001',
        description: 'Adjustable Wrench 12 inch',
        category: 'Tools',
        subCategory: 'Wrenches',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 950.00,
        qty: 60,
        imageUrl: 'https://example.com/images/tl001.jpg',
        discountAmount: 95.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL002' },
      update: {},
      create: {
        itemCode: 'TL002',
        description: 'Combination Pliers 8 inch',
        category: 'Tools',
        subCategory: 'Pliers',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 420.00,
        qty: 90,
        imageUrl: 'https://example.com/images/tl002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL003' },
      update: {},
      create: {
        itemCode: 'TL003',
        description: 'Claw Hammer 16oz',
        category: 'Tools',
        subCategory: 'Hammers',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 380.00,
        qty: 110,
        imageUrl: 'https://example.com/images/tl003.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL004' },
      update: {},
      create: {
        itemCode: 'TL004',
        description: 'Spirit Level 24 inch',
        category: 'Tools',
        subCategory: 'Measuring',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 600.00,
        qty: 70,
        imageUrl: 'https://example.com/images/tl004.jpg',
        discountAmount: 60.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL005' },
      update: {},
      create: {
        itemCode: 'TL005',
        description: 'Tape Measure 5m',
        category: 'Tools',
        subCategory: 'Measuring',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 250.00,
        qty: 150,
        imageUrl: 'https://example.com/images/tl005.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL006' },
      update: {},
      create: {
        itemCode: 'TL006',
        description: 'Utility Knife with 5 Blades',
        category: 'Tools',
        subCategory: 'Cutting',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 180.00,
        qty: 130,
        imageUrl: 'https://example.com/images/tl006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL007' },
      update: {},
      create: {
        itemCode: 'TL007',
        description: 'Cordless Drill 12V',
        category: 'Tools',
        subCategory: 'Power Tools',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 6500.00,
        qty: 25,
        imageUrl: 'https://example.com/images/tl007.jpg',
        discountAmount: 650.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL008' },
      update: {},
      create: {
        itemCode: 'TL008',
        description: 'Angle Grinder 4 inch',
        category: 'Tools',
        subCategory: 'Power Tools',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 4200.00,
        qty: 30,
        imageUrl: 'https://example.com/images/tl008.jpg',
        discountAmount: 420.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL009' },
      update: {},
      create: {
        itemCode: 'TL009',
        description: 'Circular Saw 7 inch',
        category: 'Tools',
        subCategory: 'Power Tools',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 7800.00,
        qty: 18,
        imageUrl: 'https://example.com/images/tl009.jpg',
        discountAmount: 780.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'TL010' },
      update: {},
      create: {
        itemCode: 'TL010',
        description: 'Sledge Hammer 4kg',
        category: 'Tools',
        subCategory: 'Hammers',
        categoryCode: 'TL',
        uom: 'PCS',
        price: 1200.00,
        qty: 40,
        imageUrl: 'https://example.com/images/tl010.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FA001' },
      update: {},
      create: {
        itemCode: 'FA001',
        description: 'Hex Bolt M8x50mm (Pack of 50)',
        category: 'Fasteners',
        subCategory: 'Bolts',
        categoryCode: 'FA',
        uom: 'PKT',
        price: 600.00,
        qty: 80,
        imageUrl: 'https://example.com/images/fa001.jpg',
        discountAmount: 60.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FA002' },
      update: {},
      create: {
        itemCode: 'FA002',
        description: 'Nylon Wall Plug 8mm (Pack of 100)',
        category: 'Fasteners',
        subCategory: 'Wall Plugs',
        categoryCode: 'FA',
        uom: 'PKT',
        price: 350.00,
        qty: 120,
        imageUrl: 'https://example.com/images/fa002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FA003' },
      update: {},
      create: {
        itemCode: 'FA003',
        description: 'Wood Screw 1 inch (Pack of 100)',
        category: 'Fasteners',
        subCategory: 'Screws',
        categoryCode: 'FA',
        uom: 'PKT',
        price: 200.00,
        qty: 140,
        imageUrl: 'https://example.com/images/fa003.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FA004' },
      update: {},
      create: {
        itemCode: 'FA004',
        description: 'Spring Washer M10 (Pack of 50)',
        category: 'Fasteners',
        subCategory: 'Washers',
        categoryCode: 'FA',
        uom: 'PKT',
        price: 180.00,
        qty: 100,
        imageUrl: 'https://example.com/images/fa004.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FA005' },
      update: {},
      create: {
        itemCode: 'FA005',
        description: 'Anchor Bolt 12x100mm (Pack of 10)',
        category: 'Fasteners',
        subCategory: 'Bolts',
        categoryCode: 'FA',
        uom: 'PKT',
        price: 900.00,
        qty: 60,
        imageUrl: 'https://example.com/images/fa005.jpg',
        discountAmount: 90.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'AD001' },
      update: {},
      create: {
        itemCode: 'AD001',
        description: 'Epoxy Adhesive 1kg',
        category: 'Adhesives',
        subCategory: 'Epoxy',
        categoryCode: 'AD',
        uom: 'KG',
        price: 1200.00,
        qty: 35,
        imageUrl: 'https://example.com/images/ad001.jpg',
        discountAmount: 120.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'AD002' },
      update: {},
      create: {
        itemCode: 'AD002',
        description: 'PVC Solvent Cement 500ml',
        category: 'Adhesives',
        subCategory: 'PVC',
        categoryCode: 'AD',
        uom: 'TIN',
        price: 350.00,
        qty: 80,
        imageUrl: 'https://example.com/images/ad002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'AD003' },
      update: {},
      create: {
        itemCode: 'AD003',
        description: 'Contact Adhesive 1L',
        category: 'Adhesives',
        subCategory: 'Contact',
        categoryCode: 'AD',
        uom: 'TIN',
        price: 600.00,
        qty: 60,
        imageUrl: 'https://example.com/images/ad003.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FL001' },
      update: {},
      create: {
        itemCode: 'FL001',
        description: 'Ceramic Floor Tile 12x12 inch',
        category: 'Flooring',
        subCategory: 'Tiles',
        categoryCode: 'FL',
        uom: 'BOX',
        price: 3200.00,
        qty: 45,
        imageUrl: 'https://example.com/images/fl001.jpg',
        discountAmount: 320.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FL002' },
      update: {},
      create: {
        itemCode: 'FL002',
        description: 'Vinyl Flooring Roll 2mm',
        category: 'Flooring',
        subCategory: 'Vinyl',
        categoryCode: 'FL',
        uom: 'ROLL',
        price: 4500.00,
        qty: 20,
        imageUrl: 'https://example.com/images/fl002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'FL003' },
      update: {},
      create: {
        itemCode: 'FL003',
        description: 'Laminate Flooring 8mm',
        category: 'Flooring',
        subCategory: 'Laminate',
        categoryCode: 'FL',
        uom: 'BOX',
        price: 3800.00,
        qty: 30,
        imageUrl: 'https://example.com/images/fl003.jpg',
        discountAmount: 380.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'RF001' },
      update: {},
      create: {
        itemCode: 'RF001',
        description: 'Corrugated Roofing Sheet 8ft',
        category: 'Roofing',
        subCategory: 'Sheets',
        categoryCode: 'RF',
        uom: 'PCS',
        price: 1800.00,
        qty: 70,
        imageUrl: 'https://example.com/images/rf001.jpg',
        discountAmount: 180.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'RF002' },
      update: {},
      create: {
        itemCode: 'RF002',
        description: 'Bitumen Roofing Felt 1x10m',
        category: 'Roofing',
        subCategory: 'Felt',
        categoryCode: 'RF',
        uom: 'ROLL',
        price: 2200.00,
        qty: 25,
        imageUrl: 'https://example.com/images/rf002.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'RF003' },
      update: {},
      create: {
        itemCode: 'RF003',
        description: 'Roof Ridge Cap 2ft',
        category: 'Roofing',
        subCategory: 'Accessories',
        categoryCode: 'RF',
        uom: 'PCS',
        price: 350.00,
        qty: 90,
        imageUrl: 'https://example.com/images/rf003.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'RF004' },
      update: {},
      create: {
        itemCode: 'RF004',
        description: 'Polycarbonate Roofing Sheet 6ft',
        category: 'Roofing',
        subCategory: 'Sheets',
        categoryCode: 'RF',
        uom: 'PCS',
        price: 3200.00,
        qty: 40,
        imageUrl: 'https://example.com/images/rf004.jpg',
        discountAmount: 320.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL004' },
      update: {},
      create: {
        itemCode: 'EL004',
        description: 'LED Flood Light 50W',
        category: 'Electrical',
        subCategory: 'Lighting',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 2200.00,
        qty: 55,
        imageUrl: 'https://example.com/images/el004.jpg',
        discountAmount: 220.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL005' },
      update: {},
      create: {
        itemCode: 'EL005',
        description: 'Extension Cord 5m',
        category: 'Electrical',
        subCategory: 'Accessories',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 650.00,
        qty: 100,
        imageUrl: 'https://example.com/images/el005.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL006' },
      update: {},
      create: {
        itemCode: 'EL006',
        description: 'Miniature Circuit Breaker 16A',
        category: 'Electrical',
        subCategory: 'Circuit Breakers',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 320.00,
        qty: 120,
        imageUrl: 'https://example.com/images/el006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL007' },
      update: {},
      create: {
        itemCode: 'EL007',
        description: 'Electrical Tape Black',
        category: 'Electrical',
        subCategory: 'Accessories',
        categoryCode: 'EL',
        uom: 'ROLL',
        price: 60.00,
        qty: 300,
        imageUrl: 'https://example.com/images/el007.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL008' },
      update: {},
      create: {
        itemCode: 'EL008',
        description: 'Plug Top 13A',
        category: 'Electrical',
        subCategory: 'Accessories',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 120.00,
        qty: 180,
        imageUrl: 'https://example.com/images/el008.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL009' },
      update: {},
      create: {
        itemCode: 'EL009',
        description: 'LED Panel Light 18W',
        category: 'Electrical',
        subCategory: 'Lighting',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 950.00,
        qty: 70,
        imageUrl: 'https://example.com/images/el009.jpg',
        discountAmount: 95.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'EL010' },
      update: {},
      create: {
        itemCode: 'EL010',
        description: 'Ceiling Rose White',
        category: 'Electrical',
        subCategory: 'Accessories',
        categoryCode: 'EL',
        uom: 'PCS',
        price: 80.00,
        qty: 250,
        imageUrl: 'https://example.com/images/el010.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL003' },
      update: {},
      create: {
        itemCode: 'PL003',
        description: 'Shower Mixer Set',
        category: 'Plumbing',
        subCategory: 'Taps',
        categoryCode: 'PL',
        uom: 'SET',
        price: 3200.00,
        qty: 35,
        imageUrl: 'https://example.com/images/pl003.jpg',
        discountAmount: 320.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL004' },
      update: {},
      create: {
        itemCode: 'PL004',
        description: 'Flexible Hose 1.5m',
        category: 'Plumbing',
        subCategory: 'Hoses',
        categoryCode: 'PL',
        uom: 'PCS',
        price: 180.00,
        qty: 90,
        imageUrl: 'https://example.com/images/pl004.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL005' },
      update: {},
      create: {
        itemCode: 'PL005',
        description: 'Ball Valve 1 inch',
        category: 'Plumbing',
        subCategory: 'Valves',
        categoryCode: 'PL',
        uom: 'PCS',
        price: 420.00,
        qty: 60,
        imageUrl: 'https://example.com/images/pl005.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL006' },
      update: {},
      create: {
        itemCode: 'PL006',
        description: 'PVC Elbow 90° 2 inch',
        category: 'Plumbing',
        subCategory: 'Fittings',
        categoryCode: 'PL',
        uom: 'PCS',
        price: 60.00,
        qty: 200,
        imageUrl: 'https://example.com/images/pl006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PL007' },
      update: {},
      create: {
        itemCode: 'PL007',
        description: 'Brass Bib Tap 1/2 inch',
        category: 'Plumbing',
        subCategory: 'Taps',
        categoryCode: 'PL',
        uom: 'PCS',
        price: 320.00,
        qty: 80,
        imageUrl: 'https://example.com/images/pl007.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA003' },
      update: {},
      create: {
        itemCode: 'PA003',
        description: 'Exterior Paint 10L',
        category: 'Paint',
        subCategory: 'Exterior',
        categoryCode: 'PA',
        uom: 'CAN',
        price: 3200.00,
        qty: 30,
        imageUrl: 'https://example.com/images/pa003.jpg',
        discountAmount: 320.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA004' },
      update: {},
      create: {
        itemCode: 'PA004',
        description: 'Primer Sealer 5L',
        category: 'Paint',
        subCategory: 'Primer',
        categoryCode: 'PA',
        uom: 'CAN',
        price: 1800.00,
        qty: 40,
        imageUrl: 'https://example.com/images/pa004.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA005' },
      update: {},
      create: {
        itemCode: 'PA005',
        description: 'Paint Roller 9 inch',
        category: 'Paint',
        subCategory: 'Brushes',
        categoryCode: 'PA',
        uom: 'PCS',
        price: 220.00,
        qty: 120,
        imageUrl: 'https://example.com/images/pa005.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'PA006' },
      update: {},
      create: {
        itemCode: 'PA006',
        description: 'Wall Putty 20kg',
        category: 'Paint',
        subCategory: 'Putty',
        categoryCode: 'PA',
        uom: 'BAG',
        price: 950.00,
        qty: 50,
        imageUrl: 'https://example.com/images/pa006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG003' },
      update: {},
      create: {
        itemCode: 'SG003',
        description: 'Safety Shoes Size 9',
        category: 'Safety Gear',
        subCategory: 'Shoes',
        categoryCode: 'SG',
        uom: 'PAIR',
        price: 1800.00,
        qty: 60,
        imageUrl: 'https://example.com/images/sg003.jpg',
        discountAmount: 180.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG004' },
      update: {},
      create: {
        itemCode: 'SG004',
        description: 'Reflective Safety Vest',
        category: 'Safety Gear',
        subCategory: 'Vests',
        categoryCode: 'SG',
        uom: 'PCS',
        price: 350.00,
        qty: 100,
        imageUrl: 'https://example.com/images/sg004.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG005' },
      update: {},
      create: {
        itemCode: 'SG005',
        description: 'Ear Protection Muff',
        category: 'Safety Gear',
        subCategory: 'Ear Protection',
        categoryCode: 'SG',
        uom: 'PCS',
        price: 420.00,
        qty: 80,
        imageUrl: 'https://example.com/images/sg005.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG006' },
      update: {},
      create: {
        itemCode: 'SG006',
        description: 'Safety Goggles Clear',
        category: 'Safety Gear',
        subCategory: 'Goggles',
        categoryCode: 'SG',
        uom: 'PCS',
        price: 120.00,
        qty: 200,
        imageUrl: 'https://example.com/images/sg006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'SG007' },
      update: {},
      create: {
        itemCode: 'SG007',
        description: 'Respirator Mask N95',
        category: 'Safety Gear',
        subCategory: 'Masks',
        categoryCode: 'SG',
        uom: 'PCS',
        price: 180.00,
        qty: 300,
        imageUrl: 'https://example.com/images/sg007.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW005' },
      update: {},
      create: {
        itemCode: 'HW005',
        description: 'Adjustable Spanner 10 inch',
        category: 'Hardware',
        subCategory: 'Tools',
        categoryCode: 'HW',
        uom: 'PCS',
        price: 700.00,
        qty: 90,
        imageUrl: 'https://example.com/images/hw005.jpg',
        discountAmount: 70.00,
        discountPercentage: 10.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW006' },
      update: {},
      create: {
        itemCode: 'HW006',
        description: 'Pipe Wrench 18 inch',
        category: 'Hardware',
        subCategory: 'Tools',
        categoryCode: 'HW',
        uom: 'PCS',
        price: 1200.00,
        qty: 40,
        imageUrl: 'https://example.com/images/hw006.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW007' },
      update: {},
      create: {
        itemCode: 'HW007',
        description: 'Wire Brush Steel',
        category: 'Hardware',
        subCategory: 'Tools',
        categoryCode: 'HW',
        uom: 'PCS',
        price: 180.00,
        qty: 120,
        imageUrl: 'https://example.com/images/hw007.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
    prisma.product.upsert({
      where: { itemCode: 'HW008' },
      update: {},
      create: {
        itemCode: 'HW008',
        description: 'Steel Ruler 1m',
        category: 'Hardware',
        subCategory: 'Measuring',
        categoryCode: 'HW',
        uom: 'PCS',
        price: 220.00,
        qty: 80,
        imageUrl: 'https://example.com/images/hw008.jpg',
        discountAmount: 0.00,
        discountPercentage: 0.00,
        isActive: true,
      },
    }),
  ];
  const products: any[] = [];
  for (const upsert of productUpserts) {
    products.push(await upsert);
  }
  console.log('✅ Products created:', products.length);

  // Build a map from itemCode to id
  const productMap: Record<string, string> = {};
  for (const product of products) {
    productMap[product.itemCode] = product.id;
  }

  // Create sample orders (50 total records)
  const orderData = [
    // June 2025 Orders (20 orders)
    {
      orderNumber: 'ORD-1001',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'pending',
      createdAt: new Date('2025-06-01T09:00:00Z'),
      items: [
        { productId: 'HW001', quantity: 10, unitPrice: 500, discount: 0, totalAmount: 5000 },
        { productId: 'LT001', quantity: 5, unitPrice: 250, discount: 0, totalAmount: 1250 },
      ]
    },
    {
      orderNumber: 'ORD-1002',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-06-02T10:00:00Z'),
      items: [
        { productId: 'HW002', quantity: 3, unitPrice: 1200, discount: 0, totalAmount: 3600 },
      ]
    },
    {
      orderNumber: 'ORD-1003',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'processing',
      createdAt: new Date('2025-06-03T11:00:00Z'),
      items: [
        { productId: 'LT002', quantity: 8, unitPrice: 180, discount: 0, totalAmount: 1440 },
        { productId: 'EL001', quantity: 2, unitPrice: 150, discount: 0, totalAmount: 300 },
      ]
    },
    {
      orderNumber: 'ORD-1004',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'cancelled',
      createdAt: new Date('2025-06-04T12:00:00Z'),
      items: [
        { productId: 'HW003', quantity: 1, unitPrice: 850, discount: 0, totalAmount: 850 },
      ]
    },
    {
      orderNumber: 'ORD-1005',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-06-05T13:00:00Z'),
      items: [
        { productId: 'EL002', quantity: 4, unitPrice: 450, discount: 0, totalAmount: 1800 },
        { productId: 'PL001', quantity: 2, unitPrice: 1200, discount: 0, totalAmount: 2400 },
      ]
    },
    {
      orderNumber: 'ORD-1006',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'pending',
      createdAt: new Date('2025-06-06T14:00:00Z'),
      items: [
        { productId: 'PA001', quantity: 1, unitPrice: 4500, discount: 0, totalAmount: 4500 },
      ]
    },
    {
      orderNumber: 'ORD-1007',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'processing',
      createdAt: new Date('2025-06-07T15:00:00Z'),
      items: [
        { productId: 'SG001', quantity: 6, unitPrice: 350, discount: 0, totalAmount: 2100 },
        { productId: 'TL001', quantity: 2, unitPrice: 950, discount: 0, totalAmount: 1900 },
      ]
    },
    {
      orderNumber: 'ORD-1008',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-06-08T16:00:00Z'),
      items: [
        { productId: 'BM001', quantity: 1, unitPrice: 3500, discount: 0, totalAmount: 3500 },
      ]
    },
    {
      orderNumber: 'ORD-1009',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'pending',
      createdAt: new Date('2025-06-09T17:00:00Z'),
      items: [
        { productId: 'LT003', quantity: 3, unitPrice: 3500, discount: 0, totalAmount: 10500 },
      ]
    },
    {
      orderNumber: 'ORD-1010',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'cancelled',
      createdAt: new Date('2025-06-10T18:00:00Z'),
      items: [
        { productId: 'FA001', quantity: 2, unitPrice: 600, discount: 0, totalAmount: 1200 },
      ]
    },
    {
      orderNumber: 'ORD-1011',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'processing',
      createdAt: new Date('2025-06-11T19:00:00Z'),
      items: [
        { productId: 'AD001', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
        { productId: 'FL001', quantity: 1, unitPrice: 3200, discount: 0, totalAmount: 3200 },
      ]
    },
    {
      orderNumber: 'ORD-1012',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-06-12T20:00:00Z'),
      items: [
        { productId: 'RF001', quantity: 5, unitPrice: 1800, discount: 0, totalAmount: 9000 },
      ]
    },
    {
      orderNumber: 'ORD-1013',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'pending',
      createdAt: new Date('2025-06-13T21:00:00Z'),
      items: [
        { productId: 'EL004', quantity: 2, unitPrice: 2200, discount: 0, totalAmount: 4400 },
      ]
    },
    {
      orderNumber: 'ORD-1014',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'processing',
      createdAt: new Date('2025-06-14T22:00:00Z'),
      items: [
        { productId: 'PL002', quantity: 1, unitPrice: 850, discount: 0, totalAmount: 850 },
      ]
    },
    {
      orderNumber: 'ORD-1015',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-06-15T23:00:00Z'),
      items: [
        { productId: 'PA002', quantity: 1, unitPrice: 120, discount: 0, totalAmount: 120 },
        { productId: 'SG002', quantity: 2, unitPrice: 280, discount: 0, totalAmount: 560 },
      ]
    },
    {
      orderNumber: 'ORD-1016',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'cancelled',
      createdAt: new Date('2025-06-16T08:00:00Z'),
      items: [
        { productId: 'TL007', quantity: 1, unitPrice: 6500, discount: 0, totalAmount: 6500 },
      ]
    },
    {
      orderNumber: 'ORD-1017',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'pending',
      createdAt: new Date('2025-06-17T09:00:00Z'),
      items: [
        { productId: 'HW004', quantity: 4, unitPrice: 450, discount: 0, totalAmount: 1800 },
      ]
    },
    {
      orderNumber: 'ORD-1018',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'processing',
      createdAt: new Date('2025-06-18T10:00:00Z'),
      items: [
        { productId: 'BM002', quantity: 100, unitPrice: 25, discount: 0, totalAmount: 2500 },
      ]
    },
    {
      orderNumber: 'ORD-1019',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-06-19T11:00:00Z'),
      items: [
        { productId: 'EL005', quantity: 3, unitPrice: 650, discount: 0, totalAmount: 1950 },
      ]
    },
    {
      orderNumber: 'ORD-1020',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'pending',
      createdAt: new Date('2025-06-20T12:00:00Z'),
      items: [
        { productId: 'SG004', quantity: 5, unitPrice: 350, discount: 0, totalAmount: 1750 },
      ]
    },
    // May 2025 Orders (15 orders)
    {
      orderNumber: 'ORD-2001',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-01T13:00:00Z'),
      items: [
        { productId: 'HW001', quantity: 8, unitPrice: 500, discount: 0, totalAmount: 4000 },
      ]
    },
    {
      orderNumber: 'ORD-2002',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-02T14:00:00Z'),
      items: [
        { productId: 'HW002', quantity: 2, unitPrice: 1200, discount: 0, totalAmount: 2400 },
      ]
    },
    {
      orderNumber: 'ORD-2003',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-03T15:00:00Z'),
      items: [
        { productId: 'LT001', quantity: 3, unitPrice: 250, discount: 0, totalAmount: 750 },
      ]
    },
    {
      orderNumber: 'ORD-2004',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-04T16:00:00Z'),
      items: [
        { productId: 'EL001', quantity: 1, unitPrice: 150, discount: 0, totalAmount: 150 },
      ]
    },
    {
      orderNumber: 'ORD-2005',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-05T17:00:00Z'),
      items: [
        { productId: 'HW003', quantity: 2, unitPrice: 850, discount: 0, totalAmount: 1700 },
      ]
    },
    {
      orderNumber: 'ORD-2006',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-06T18:00:00Z'),
      items: [
        { productId: 'LT002', quantity: 5, unitPrice: 180, discount: 0, totalAmount: 900 },
      ]
    },
    {
      orderNumber: 'ORD-2007',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-07T19:00:00Z'),
      items: [
        { productId: 'EL002', quantity: 3, unitPrice: 450, discount: 0, totalAmount: 1350 },
      ]
    },
    {
      orderNumber: 'ORD-2008',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-08T20:00:00Z'),
      items: [
        { productId: 'PL001', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
      ]
    },
    {
      orderNumber: 'ORD-2009',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-09T21:00:00Z'),
      items: [
        { productId: 'PA001', quantity: 1, unitPrice: 4500, discount: 0, totalAmount: 4500 },
      ]
    },
    {
      orderNumber: 'ORD-2010',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-10T22:00:00Z'),
      items: [
        { productId: 'SG001', quantity: 4, unitPrice: 350, discount: 0, totalAmount: 1400 },
      ]
    },
    {
      orderNumber: 'ORD-2011',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-11T23:00:00Z'),
      items: [
        { productId: 'TL001', quantity: 1, unitPrice: 950, discount: 0, totalAmount: 950 },
      ]
    },
    {
      orderNumber: 'ORD-2012',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-12T08:00:00Z'),
      items: [
        { productId: 'BM001', quantity: 1, unitPrice: 3500, discount: 0, totalAmount: 3500 },
      ]
    },
    {
      orderNumber: 'ORD-2013',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-13T09:00:00Z'),
      items: [
        { productId: 'LT003', quantity: 2, unitPrice: 3500, discount: 0, totalAmount: 7000 },
      ]
    },
    {
      orderNumber: 'ORD-2014',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-05-14T10:00:00Z'),
      items: [
        { productId: 'FA001', quantity: 1, unitPrice: 600, discount: 0, totalAmount: 600 },
      ]
    },
    {
      orderNumber: 'ORD-2015',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-05-15T11:00:00Z'),
      items: [
        { productId: 'AD001', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
      ]
    },
    // April 2025 Orders (10 orders)
    {
      orderNumber: 'ORD-3001',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-01T12:00:00Z'),
      items: [
        { productId: 'HW001', quantity: 6, unitPrice: 500, discount: 0, totalAmount: 3000 },
      ]
    },
    {
      orderNumber: 'ORD-3002',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-02T13:00:00Z'),
      items: [
        { productId: 'HW002', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
      ]
    },
    {
      orderNumber: 'ORD-3003',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-04-03T14:00:00Z'),
      items: [
        { productId: 'LT001', quantity: 2, unitPrice: 250, discount: 0, totalAmount: 500 },
      ]
    },
    {
      orderNumber: 'ORD-3004',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-04-04T15:00:00Z'),
      items: [
        { productId: 'EL001', quantity: 1, unitPrice: 150, discount: 0, totalAmount: 150 },
      ]
    },
    {
      orderNumber: 'ORD-3005',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-05T16:00:00Z'),
      items: [
        { productId: 'HW003', quantity: 1, unitPrice: 850, discount: 0, totalAmount: 850 },
      ]
    },
    {
      orderNumber: 'ORD-3006',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-06T17:00:00Z'),
      items: [
        { productId: 'LT002', quantity: 3, unitPrice: 180, discount: 0, totalAmount: 540 },
      ]
    },
    {
      orderNumber: 'ORD-3007',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-04-07T18:00:00Z'),
      items: [
        { productId: 'EL002', quantity: 2, unitPrice: 450, discount: 0, totalAmount: 900 },
      ]
    },
    {
      orderNumber: 'ORD-3008',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-04-08T19:00:00Z'),
      items: [
        { productId: 'PL001', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
      ]
    },
    {
      orderNumber: 'ORD-3009',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-09T20:00:00Z'),
      items: [
        { productId: 'PA001', quantity: 1, unitPrice: 4500, discount: 0, totalAmount: 4500 },
      ]
    },
    {
      orderNumber: 'ORD-3010',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-04-10T21:00:00Z'),
      items: [
        { productId: 'SG001', quantity: 3, unitPrice: 350, discount: 0, totalAmount: 1050 },
      ]
    },
    // March 2025 Orders (5 orders)
    {
      orderNumber: 'ORD-4001',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-03-01T10:00:00Z'),
      items: [
        { productId: 'HW001', quantity: 4, unitPrice: 500, discount: 0, totalAmount: 2000 },
      ]
    },
    {
      orderNumber: 'ORD-4002',
      customerId: 'CUST002',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-03-02T11:00:00Z'),
      items: [
        { productId: 'HW002', quantity: 1, unitPrice: 1200, discount: 0, totalAmount: 1200 },
      ]
    },
    {
      orderNumber: 'ORD-4003',
      customerId: 'CUST001',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-03-03T12:00:00Z'),
      items: [
        { productId: 'LT001', quantity: 1, unitPrice: 250, discount: 0, totalAmount: 250 },
      ]
    },
    {
      orderNumber: 'ORD-4004',
      customerId: 'CUST002',
      salespersonId: 'EXE002',
      status: 'completed',
      createdAt: new Date('2025-03-04T13:00:00Z'),
      items: [
        { productId: 'EL001', quantity: 1, unitPrice: 150, discount: 0, totalAmount: 150 },
      ]
    },
    {
      orderNumber: 'ORD-4005',
      customerId: 'CUST001',
      salespersonId: 'EXE001',
      status: 'completed',
      createdAt: new Date('2025-03-05T14:00:00Z'),
      items: [
        { productId: 'HW003', quantity: 1, unitPrice: 850, discount: 0, totalAmount: 850 },
      ]
    },
  ];

  // Map productId in order items from itemCode to UUID
  const fixedOrderData = orderData.map(order => ({
    ...order,
    items: order.items.map(item => ({
      ...item,
      productId: productMap[item.productId],
    })),
  }));

  // Create orders sequentially to avoid connection pool timeout
  const orders: any[] = [];
  for (const orderData of fixedOrderData) {
    const order = await prisma.order.upsert({
      where: { orderNumber: orderData.orderNumber },
      update: {
        customerId: orderData.customerId,
        salespersonId: orderData.salespersonId,
        status: orderData.status,
        createdAt: orderData.createdAt,
        jsonPayload: JSON.stringify(orderData),
        // Update order items by deleting existing ones and creating new ones
        orderItems: {
          deleteMany: {},
          create: orderData.items,
        },
      },
      create: {
        orderNumber: orderData.orderNumber,
        customerId: orderData.customerId,
        salespersonId: orderData.salespersonId,
        status: orderData.status,
        createdAt: orderData.createdAt,
        jsonPayload: JSON.stringify(orderData),
        orderItems: {
          create: orderData.items,
        },
      },
    });
    orders.push(order);
  }
  console.log('✅ Orders created:', orders.length);

  // Create sample invoices
  const invoices = await Promise.all([
    prisma.invoice.upsert({
      where: { documentNo: 'INV001' },
      update: {},
      create: {
        customerId: 'CUST001',
        documentNo: 'INV001',
        docDate: new Date('2024-01-15'),
        docAmount: 50000.00,
        daysDue: 15,
        docType: 'IN',
        dueAmount: 50000.00,
        exeId: 'EXE001',
        refNo: 'REF001',
      },
    }),
    prisma.invoice.upsert({
      where: { documentNo: 'INV002' },
      update: {},
      create: {
        customerId: 'CUST002',
        documentNo: 'INV002',
        docDate: new Date('2024-01-20'),
        docAmount: 150000.00,
        daysDue: 10,
        docType: 'IN',
        dueAmount: 150000.00,
        exeId: 'EXE001',
        refNo: 'REF002',
      },
    }),
  ]);

  console.log('✅ Invoices created:', invoices.length);

  // Create sample sales reports
  const salesReports = await Promise.all([
    // Sales data for current month (June 2025)
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-15'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch',
        category: 'Hardware',
        subCategory: 'Nails',
        quantity: 100,
        unitPrice: 500.00,
        totalSales: 50000.00,
        discount: 5000.00,
        netSales: 45000.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-20'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'HW002',
        productName: 'Cement Portland 50kg',
        category: 'Building Materials',
        subCategory: 'Cement',
        quantity: 200,
        unitPrice: 1200.00,
        totalSales: 240000.00,
        discount: 0.00,
        netSales: 240000.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-25'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White',
        category: 'Lighting',
        subCategory: 'LED Bulbs',
        quantity: 500,
        unitPrice: 250.00,
        totalSales: 125000.00,
        discount: 12500.00,
        netSales: 112500.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-28'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'EL001',
        productName: 'Electrical Wire 2.5mm',
        category: 'Electrical',
        subCategory: 'Wires',
        quantity: 1000,
        unitPrice: 150.00,
        totalSales: 150000.00,
        discount: 0.00,
        netSales: 150000.00,
      },
    }),
    // Additional sales for better metrics
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-10'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch',
        category: 'Hardware',
        subCategory: 'Nails',
        quantity: 50,
        unitPrice: 500.00,
        totalSales: 25000.00,
        discount: 2500.00,
        netSales: 22500.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-12'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'HW002',
        productName: 'Cement Portland 50kg',
        category: 'Building Materials',
        subCategory: 'Cement',
        quantity: 150,
        unitPrice: 1200.00,
        totalSales: 180000.00,
        discount: 0.00,
        netSales: 180000.00,
      },
    }),
  ]);

  console.log('✅ Sales reports created:', salesReports.length);

  // Create sample collections data
  const collections = await Promise.all([
    prisma.payment.upsert({
      where: { transNo: 'PAY001' },
      update: {},
      create: {
        customerId: 'CUST001',
        transNo: 'PAY001',
        transDate: new Date('2025-06-10'),
        amtBc: 45000.00,
        remUnappl: 5000.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAY002' },
      update: {},
      create: {
        customerId: 'CUST002',
        transNo: 'PAY002',
        transDate: new Date('2025-06-18'),
        amtBc: 120000.00,
        remUnappl: 30000.00,
      },
    }),
    // Additional collections for current month
    prisma.payment.upsert({
      where: { transNo: 'PAY003' },
      update: {},
      create: {
        customerId: 'CUST001',
        transNo: 'PAY003',
        transDate: new Date('2025-06-22'),
        amtBc: 67500.00,
        remUnappl: 0.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAY004' },
      update: {},
      create: {
        customerId: 'CUST002',
        transNo: 'PAY004',
        transDate: new Date('2025-06-25'),
        amtBc: 180000.00,
        remUnappl: 0.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAY005' },
      update: {},
      create: {
        customerId: 'CUST001',
        transNo: 'PAY005',
        transDate: new Date('2025-06-28'),
        amtBc: 112500.00,
        remUnappl: 0.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAY006' },
      update: {},
      create: {
        customerId: 'CUST002',
        transNo: 'PAY006',
        transDate: new Date('2025-06-30'),
        amtBc: 150000.00,
        remUnappl: 0.00,
      },
    }),
  ]);

  console.log('✅ Collections created:', collections.length);

  // Create sample returns data
  const returns = await Promise.all([
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-18'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch (RETURN)',
        category: 'Hardware',
        subCategory: 'Nails',
        quantity: -10, // Negative quantity indicates return
        unitPrice: 500.00,
        totalSales: -5000.00,
        discount: -500.00,
        netSales: -4500.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-22'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White (RETURN)',
        category: 'Lighting',
        subCategory: 'LED Bulbs',
        quantity: -20, // Negative quantity indicates return
        unitPrice: 250.00,
        totalSales: -5000.00,
        discount: -500.00,
        netSales: -4500.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-25'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'EL001',
        productName: 'Electrical Wire 2.5mm (RETURN)',
        category: 'Electrical',
        subCategory: 'Wires',
        quantity: -50, // Negative quantity indicates return
        unitPrice: 150.00,
        totalSales: -7500.00,
        discount: 0.00,
        netSales: -7500.00,
      },
    }),
  ]);

  console.log('✅ Returns created:', returns.length);

  // Create sample replacements data (similar to returns but with different product)
  const replacements = await Promise.all([
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-20'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW002',
        productName: 'Cement Portland 50kg (REPLACEMENT)',
        category: 'Replacement',
        subCategory: 'Cement',
        quantity: 5, // Positive quantity for replacement
        unitPrice: 1200.00,
        totalSales: 6000.00,
        discount: 0.00,
        netSales: 6000.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-24'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White (REPLACEMENT)',
        category: 'Replacement',
        subCategory: 'LED Bulbs',
        quantity: 15, // Positive quantity for replacement
        unitPrice: 250.00,
        totalSales: 3750.00,
        discount: 375.00,
        netSales: 3375.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-06-27'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch (REPLACEMENT)',
        category: 'Replacement',
        subCategory: 'Nails',
        quantity: 8, // Positive quantity for replacement
        unitPrice: 500.00,
        totalSales: 4000.00,
        discount: 400.00,
        netSales: 3600.00,
      },
    }),
  ]);

  console.log('✅ Replacements created:', replacements.length);

  // Add May 2025 sales reports for previous month comparison
  const maySalesReports = await Promise.all([
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-15'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch',
        category: 'Hardware',
        subCategory: 'Nails',
        quantity: 80,
        unitPrice: 500.00,
        totalSales: 40000.00,
        discount: 4000.00,
        netSales: 36000.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-20'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'HW002',
        productName: 'Cement Portland 50kg',
        category: 'Building Materials',
        subCategory: 'Cement',
        quantity: 150,
        unitPrice: 1200.00,
        totalSales: 180000.00,
        discount: 0.00,
        netSales: 180000.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-25'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White',
        category: 'Lighting',
        subCategory: 'LED Bulbs',
        quantity: 300,
        unitPrice: 250.00,
        totalSales: 75000.00,
        discount: 7500.00,
        netSales: 67500.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-28'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'EL001',
        productName: 'Electrical Wire 2.5mm',
        category: 'Electrical',
        subCategory: 'Wires',
        quantity: 600,
        unitPrice: 150.00,
        totalSales: 90000.00,
        discount: 0.00,
        netSales: 90000.00,
      },
    }),
  ]);
  console.log('✅ May Sales reports created:', maySalesReports.length);

  // Add May 2025 collections
  const mayCollections = await Promise.all([
    prisma.payment.upsert({
      where: { transNo: 'PAYMAY001' },
      update: {},
      create: {
        customerId: 'CUST001',
        transNo: 'PAYMAY001',
        transDate: new Date('2025-05-10'),
        amtBc: 36000.00,
        remUnappl: 4000.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAYMAY002' },
      update: {},
      create: {
        customerId: 'CUST002',
        transNo: 'PAYMAY002',
        transDate: new Date('2025-05-18'),
        amtBc: 180000.00,
        remUnappl: 0.00,
      },
    }),
    prisma.payment.upsert({
      where: { transNo: 'PAYMAY003' },
      update: {},
      create: {
        customerId: 'CUST001',
        transNo: 'PAYMAY003',
        transDate: new Date('2025-05-25'),
        amtBc: 67500.00,
        remUnappl: 0.00,
      },
    }),
  ]);
  console.log('✅ May Collections created:', mayCollections.length);

  // Add May 2025 returns
  const mayReturns = await Promise.all([
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-18'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW001',
        productName: 'Steel Nails 3 inch (RETURN)',
        category: 'Hardware',
        subCategory: 'Nails',
        quantity: -5,
        unitPrice: 500.00,
        totalSales: -2500.00,
        discount: -250.00,
        netSales: -2250.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-22'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White (RETURN)',
        category: 'Lighting',
        subCategory: 'LED Bulbs',
        quantity: -10,
        unitPrice: 250.00,
        totalSales: -2500.00,
        discount: -250.00,
        netSales: -2250.00,
      },
    }),
  ]);
  console.log('✅ May Returns created:', mayReturns.length);

  // Add May 2025 replacements
  const mayReplacements = await Promise.all([
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-20'),
        customerId: 'CUST001',
        customerName: 'Colombo Hardware Store',
        city: 'Colombo',
        province: 'Western',
        productId: 'HW002',
        productName: 'Cement Portland 50kg (REPLACEMENT)',
        category: 'Replacement',
        subCategory: 'Cement',
        quantity: 2,
        unitPrice: 1200.00,
        totalSales: 2400.00,
        discount: 0.00,
        netSales: 2400.00,
      },
    }),
    prisma.salesReport.create({
      data: {
        date: new Date('2025-05-24'),
        customerId: 'CUST002',
        customerName: 'Kalutara Construction Co',
        city: 'Kalutara',
        province: 'Western',
        productId: 'LT001',
        productName: 'LED Bulb 9W Warm White (REPLACEMENT)',
        category: 'Replacement',
        subCategory: 'LED Bulbs',
        quantity: 5,
        unitPrice: 250.00,
        totalSales: 1250.00,
        discount: 125.00,
        netSales: 1125.00,
      },
    }),
  ]);
  console.log('✅ May Replacements created:', mayReplacements.length);

  console.log('🎉 Database seeding completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error during seeding:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  }); 